apiVersion: apps/v1
kind: Deployment
metadata:
  name: declarative-deployment
  labels:
    app: go-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: alex501020/lesson1:v0.3
        ports:
        - containerPort: 8080