apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: lesson14
  labels:
    app: goweb
spec:
  containers:
    - name: web
      image: alex501020/lesson1:v0.3
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP